<?php
/**
 * @var \TinyBoard\Blocks\Boards $this
 */
?>
<div class="boards-container">
<h3>Boards</h3>
<?php $boards = $this->getBoards(); ?>
	<ul>
	<?php
	/**
	 * @var \TinyBoard\Objects\Board $key
	 */
	foreach ($boards as $key ) {
		?>
		<li><a href="<?php echo \TinyBoard\TinyBoard::getUrl("board/view/".$key->getData('name'))?>"><?php echo $key->getData('description') ?></a></li>
		<?php
	}
?>
	</ul>
</div>
