<div class="container-top">
    <div class ="board-logo">
        <a href="<?php echo \TinyBoard\TinyBoard::getUrl()?>"><img src="<?php echo \TinyBoard\TinyBoard::getMedia("logo.png")?>"></a>
    </div>
</div>

<div class="content-container">

    <div class="cms-content text-container">
        <?php
            echo \TinyBoard\TinyBoard::getModel('\TinyBoard\Objects\CmsBlock')->load("about","key")->getData("data");
        ?>
    </div>
    <div class="boards-list text-container">
        <?php  \TinyBoard\TinyBoard::getBlock("\TinyBoard\Blocks\Boards", true)->renderChild(); ?>
    </div>

</div>