<div class="default-container">
    <div class="logo">LOGO</div>
    <div class="menu">
        <strong><a>Teste</a></strong>
    </div>

    <div class="cms-content">
        <?php /*
                @TODO: echo cms content
            */ ?>
    </div>
    <div class="boards-list">
        <?php  \TinyBoard\TinyBoard::getBlock("\TinyBoard\Blocks\Boards", true)->renderChild(); ?>
    </div>

</div>