
<?php
/**
 * @var TinyBoard\Objects\Post $post
 * */
$post = $this->getPost();
?>
<div class="post">
	<?php $imageData = $post->getImage()->getResolution() ?>
    <div class="fileText">
        <span class="file-info"><a href="" target="_blank" download="<?php echo $post->getImage()->getData('name') ?>.<?php echo $post->getImage()->getData('filetype')?>"><?php echo $post->getImage()->getData('name') ?>.<?php echo $post->getImage()->getData('filetype')?></a> ( <?php echo $post->getImage()->getSize() ?>, <?php echo $imageData[0] ?>x<?php echo $imageData[1] ?>)</span>
    </div>
	<div class="post-content" id="post-content_<?php echo $post->getId() ?>">
		<div class="post-header">
			<span class="subject"><?php echo $post->getSubject() ?></span>
			<span class="name"><?php echo $post->getName() ?></span>
			<span class="date"><?php echo $post->getDate() ?></span>
			<span class="id">No.<?php echo $post->getID() ?></span>
		</div>
		<div class="text">
			<p><?php echo htmlentities($post->getContent()) ?></p>
		</div>
	</div>
	<div class="img-post" id="img-<?php echo $post->getId() ?>-post">
		<?php echo $this->getImage() ?>
	</div>
</div>
