<div id="postArea">
    <form name="post">
        <label for="name">Name: </label>
        <input name="name" type="text">
        <label for="subject">Subject: </label>
        <input name="subject" type="text">
        <label for="content">Content: </label>
        <textarea name="content"></textarea>
        <label for="image">Image: </label>
        <input type="file" name="image" id="image">
        <button type="button"><span>Send</span></button>
    </form>
</div>
